version: '2'

services:
  db-main:
    build: 
      context: .
      dockerfile: main/Dockerfile
    image: nlv/db-main
    volumes:
      - dbmain:/var/lib/postgresql/data
      - dbmain_log:/var/log/postgresql
    networks: 
      - postgres-barman
    environment:
      - POSTGRES_PASSWORD=1
      - BARMAN_SERVER=db-barman
  db-barman:
    build: 
      context: .
      dockerfile: barman/Dockerfile
    image: nlv/db-barman
    volumes:
      - dbbarman_var:/var/lib/barman
      - dbbarman_log:/var/log/barman
    networks: 
      - postgres-barman

volumes: 
  dbmain:
  dbmain_log:
  dbbarman_var:
  dbbarman_log:


networks:
  postgres-barman:
 
  
